trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Add Docker Build Task
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: '<your-service-connection-name>'
- task: DockerCompose@1
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    repository: 'CI-CD'
    command: 'build'
    Dockerfile: 'Dockerfile'         # <- Adjust this if it's in a subfolder
    tags: |
      latest


